### PR TITLE
Courses: Add exportation

### PR DESCRIPTION
**Pull request by victorol1**
Add courses exportation.

### CODE REVIEW

**Review by rbngzlv — COMMENTED** [review]
@victorol1 I have deleted an unused route, but I also have a couple of comments:

- Can we add specs for the presenter, and perhaps for the new export permission?
- I think that @tramuntanal told me, that we want an export button to export the whole collection of courses, as in initatives, where you can select the format (json, csv, excel).

@tramuntanal can you confirm the last point?

The rest looks good! 👍

**Comment by tramuntanal** [comment]
Yes @rbngzlv that's it, like in Proposals, for example, where there's a button at the top right of the list where you can select the export format.

**Comment by tramuntanal** [comment]
@victorol1 can you add a screenshot in the Description of the PR when you have it ready please

**Comment by victorol1** [comment]
> @victorol1 can you add a screenshot in the Description of the PR when you have it ready please
Sure thing. I'll also add new tests for the presenter and the export permission.

**Review by rbngzlv — APPROVED** [review]
LGTM @victorol1 !

**Pull request merged**
